# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: mocxd
email: mark@thegovlab.org
description: > # this means to ignore newlines until "baseurl:"
  +---[RSA 2048]----+
  |   . o+o . .+ooo.|
  |    + ..o o++....|
  |   o . o . B++ + |
  |  o . . o + *.=  |
  |   o o oS= + .   |
  |  E +   B.+      |
  |   o . o.+ .     |
  |  . . +.  .      |
  |     . o.        |
  +----[SHA256]-----+
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mocxd.github.io" # the base hostname & protocol for your site
twitter_username: mocxd
github_username:  mocxd

# Build settings
markdown: kramdown
